### ISSUE TITLE
Return a boolean from Assertf

### ISSUE THREAD

**Issue by bkmeneguello** [kinbiko/jsonassert#44]
## What problem are you trying to solve?

If the comparison fails, it could be interesting to be able to print the failed/expected JSON. With the current implementation it's not trivial detecting the assertion failure.

## Describe how you wish this package would help you solve the problem

```go
if !jsonassert.New(t).Assertf(expected, current) {
    ... print JSON ...
}

// or better yet
if !jsonassert.Equal(t, expected, current) {
     ...
}
```

**Comment by kinbiko** [comment]
Hi @bkmeneguello, thanks for raising this issue.

> If the comparison fails, it could be interesting to be able to print the failed/expected JSON

`jsonassert` prints the difference between the failed/expected JSON, and I'm struggling to imagine a use case when this isn't enough. Could you provide an example that illustrates the problem you're trying to solve?

If you just wanted to print the JSON, you can use `*testing.T.Failed()`:

```go
func TestPrintJSONAsWell(t *testing.T) {
	actual := "{}"
	expected := "[]"
	jsonassert.New(t).Assertf(actual, expected)
	if t.Failed() {
		t.Log("The failing payload was:", actual)
	}
}
```

**Comment by bkmeneguello** [comment]
Yes, let's suppose I have more assertions in my test, like in your example, but improved:
```go
func TestPrintJSONAsWell(t *testing.T) {
	actual, ok := getJsonElements() // returns: "[1, 2]", false
	assert.True(t, ok)
	expected := "[1, 2]"
	jsonassert.New(t).Assertf(actual, expected)
	if t.Failed() {
		t.Log("The failing payload was:", actual)
	}
}
```

Now I have the `t.Failed` returning "true" but the JSON assertion didn't fail. If the JSON assertion returns a boolean I could implement this correctly.

**Comment by kinbiko** [comment]
Thanks -- I understand what you're asking for.

This example doesn't seem to me like a use-case this package needs to change its API for (function under test returns two somehow independent values).
You can work around your example above by passing in your own custom [Printer](https://pkg.go.dev/github.com/kinbiko/jsonassert#Printer) type (which wraps `*testing.T`), and exposes a way to tell if the Assertf call invoked `Errorf`.

Something like:

```go
type myPrinter struct {
    t *testing.T
    called bool
}

func (p *myPrinter) Errorf(...) {
    p.t.Helper()
    p.called = true
    p.t.Errorf(...)
}
```

Marking this issue as resolved, but willing to consider reopening if I see an argument strong enough to justify a major version bump/adding a method.
